image: alpine

.build: &build
  script:
    - mkdir public
    - cp index.html public/
    - cp -r js public/
  artifacts:
    paths:
      - public

pages:
  <<: *build
  only:
    - main

preview:
  <<: *build
  except:
    - main
